### ISSUE TITLE
pkl.load TypeError: load() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by southernduck** [amsukdu/SimplePythonNeuralNetwork#4]
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    le.classes_ = unpickle(sys.path[0] + '/batches.meta')['label_names']
  File "main.py", line 12, in unpickle
    dict = pkl.load(fo, encoding='latin1')
TypeError: load() got an unexpected keyword argument 'encoding'

**Comment by amsukdu** [comment]
I think you're using python 2.
install anaconda by python 3 and will work.

**Comment by southernduck** [comment]
yeah, python3 solved the issue.
