### ISSUE TITLE
regarding backpropogation

### ISSUE THREAD

**Issue by shashankvkt** [amsukdu/SimplePythonNeuralNetwork#7]
Hello,
Thank you very much for providing the code for CNN implementation in numpy. I am trying to understand it step by step for which I have a small query.  
Could you kindly help me with understanding that how are you backpropogating the error and updating the weights of the network in the main.py file?  (especially backprop in the conv layer)
Thanks

**Comment by amsukdu** [comment]
Hi,
Thanks for your interest but I'm not a good talker and as you already know, it's quite hard to explain in text-based comments. I would suggest you search on Google. 

https://www.jefkine.com/general/2016/09/05/backpropagation-in-convolutional-neural-networks/

This seems the closest article which explains the code that I implemented.

**Comment by shashankvkt** [comment]
Thank you very much for your feedback.
